### ISSUE TITLE
Screenshot in Readme

### ISSUE THREAD

**Issue by PySimpleGUI** [Toddly53/Roast-Report-Tool#1]
Hi there!

For tools like this that have a GUI, I've found that a lot more people stop in for a further look if there's an image of the GUI in the readme.  It's what attracts people since there are not many Python programs with GUIs.

I would like to see what your program looks like without having to clone and run it.  Hope that makes sense and doesn't make me look like a lazy bum.

**Comment by Toddly53** [comment]
> Hi there!
> 
> For tools like this that have a GUI, I've found that a lot more people stop in for a further look if there's an image of the GUI in the readme. It's what attracts people since there are not many Python programs with GUIs.
> 
> I would like to see what your program looks like without having to clone and run it. Hope that makes sense and doesn't make me look like a lazy bum.

No problem. I added a link to imgur in readme file.
